### ISSUE TITLE
Events are not sent 

### ISSUE THREAD

**Issue by sabeerulhassan** [algolia/search-insights.js#239] opened 2020-12-30 10:21 UTC
I am able to send click and filter click events successfully. 

I am trying to send some conversion events which is placed on the thank you page, and the code is placed on the body of the page, and as soon as the page loads the event is called, but I cannot see the network request in the chrome console.

I have noticed that the request is sent successfully when I trigger the event after a timeout for example after 2000 milliseconds.

The most strange thing is I am executing this code inside the `aa('getUserToken'` callback function, i get the use token, but still the event is sent only if i call this code after a timeout of more than 2 seconds.

How do we know that the event is ready to be triggered ?

**Comment by Haroenv** [comment] 2020-12-30 15:16
Hi @sabeerulhassan, do you have the version which doesn't send the event as you expect on a page somewhere where we can inspect it?

**Comment by sabeerulhassan** [comment] 2020-12-31 12:51
hi @Haroenv  we are using our staging site for testing, you can check it at https://stg-uae.sharafdg.com
If you search in the top bar for a product and click a product, then you will see the event sent in the networks tab.
Also you can see the events sent when clicking on a filter on the left side bar. 

But when you make a purchase and once you are redirected to the thankyou page, you can see the code is placed in the body which is sent only if we add it with a timeout.

If you want to make a quick purchase you can try the following product: https://stg-uae.sharafdg.com/product/eklasse-led100-polymer-power-bank-rubber-coating-10000mah-black-w-led-torch/?promo=109653

and select cash on delivery for your ease.

This is a test site so nothing will be processed.

If you wanna reproduce the issue, while you are on the thankyou page, open chrome dev tools -> network tab -> and throttle the network speed to a very slow network, in this case you can see the event will be not sent because the current timeout of 2 seconds is not enough when the network speed is slow. 

So by this behaviour I am thinking that, the event is sent successfully only after some other stuff has loaded into the browser, that's why on slower networks the loading is still not happened after the 2s timeout.

**Comment by sabeerulhassan** [comment] 2021-01-20 14:57
@Haroenv  any updates on this ?

**Comment by eunjae-lee** [comment] 2021-01-20 17:03
Hello @sabeerulhassan sorry for the late reply.
Can you show me some of your code around `getUserToken` and sending the event on your thank you page?
It'd be helpful to see how you've implemented it.

https://codesandbox.io/s/interesting-bash-rlpp6?file=/src/index.js
The example above is an empty page sending an event as soon as it's rendered.
Can you modify it to reproduce the issue if possible?

And I have a question. Why do you send a conversion event on the thank you page? Why not right after a purchase is made? If they refresh the purchase page, the conversion event might get duplicated.

**Comment by eunjae-lee** [comment] 2021-01-27 09:57
Closing the issue since we're talking on the support line.

**Closed by eunjae-lee** 2021-01-27 09:57 UTC
